### ISSUE TITLE
Convert Byte to JSON

### ISSUE THREAD

**Issue by haifahrul** [haifahrul/code-converter#4]

**Comment by MasTripunk** [comment]
I'll take this pal

**Comment by haifahrul** [comment]
My pleasure. 

For a while, please create one file js into folder `src/`, until issue #1 is done.

**Comment by SankalpaFernando** [comment]
I've made the solution for this please look at the pull request @haifahrul

**Comment by haifahrul** [comment]
@SankalpaFernando oke
